# Generated by Django 5.2.4 on 2025-07-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('next_of_kin', models.CharField(max_length=255)),
                ('next_of_kin_phone', models.CharField(max_length=15)),
                ('course', models.TextField()),
                ('result', models.IntegerField()),
                ('student_id', models.CharField(max_length=15)),
            ],
        ),
    ]
